server:
  port: 8082
spring:
  flyway:
    enabled: false
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:owta
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect